# Generated by Django 4.2.6 on 2023-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documents_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date',
            field=models.DateField(),
        ),
    ]
